application: youpipes
version: 4
runtime: go
api_version: go1

handlers:
- url: /css
  static_dir: css
- url: /img
  static_dir: img
- url: /js
  static_dir: js
- url: /favicon\.ico
  static_files: img/favicon.ico
  upload: img/favicon\.ico
- url: /robots\.txt
  static_files: templates/robots.txt
  upload: templates/robots\.txt
- url: /google841527a192bbf726\.html
  static_files: templates/google841527a192bbf726.html
  upload: templates/google841527a192bbf726\.html
- url: /google4b899b9e0462f0cd\.html
  static_files: templates/google4b899b9e0462f0cd.html
  upload: templates/google4b899b9e0462f0cd\.html  
- url: /BingSiteAuth\.xml
  static_files: templates/BingSiteAuth.xml
  upload: templates/BingSiteAuth\.xml
- url: /.*
  script: _go_app
